✨ [마이페이지] 안트코인 내역
depromeet/antoon_web pull request #219
Opened 2022-08-21 19:44 UTC by mnxmnz

## 💡 개요

![coin](https://user-images.githubusercontent.com/48766355/185808129-96f41d22-6f37-4003-8079-8262c2566961.png)

- 안트코인 내역 페이지, 안트코인 가이드 모달 생성했습니다.
- user query key 변수명, user api 함수명 변경했습니다.

## 📑 작업 사항

- [x] 안트코인 내역 페이지 생성
- [x] 안트코인 가이드 모달 생성
- [x] user query key, user api 리팩토링

## 🔎 기타

2022-08-21 23:56 UTC, choipureum requested changes
이전 PR 커밋 이력 남아있숨니당

2022-08-22 02:40 UTC, mnxmnz commented
> 이전 PR 커밋 이력 남아있숨니당

지금 rebase로  정리해서 올렸습니다 😆

2022-08-22 03:04 UTC, choipureum approved these changes
짱짱 👍

2022-08-22 03:18 UTC, merged

2022-08-22 03:18 UTC, mnxmnz commented
> 짱짱 👍

푸름님 리뷰 감사합니다!! 👍✨ 머지했습니다 🚀